#!/bin/bash

# author: hk110 (Pete Kim)
# given a set of bandwidth data, get gnuplot to plot it, embed it into a latex file, typeset it to pdf

# TODO 

DATAF=$1
OUTF=$2
PLOTFTMP="temp.tex"
PLOTTERTMP="plotter.p"

usage() { echo -e "\tUSAGE: ./plotbwdata <datafilename> <outfilename>"; }

if [ "${DATAF}" = "" ] || [ "${OUTF}" = "" ]
then
    usage;
    exit
fi

# plot data into latex
touch $PLOTTERTMP
echo -e "
    set autoscale
    set logscale x
    set terminal latex \n
    set output \"$PLOTFTMP\" \n
    plot \"$DATAF\" using 1:3 title 'p' with linespoints
" > $PLOTTERTMP
gnuplot $PLOTTERTMP
PLOT=$(<$PLOTFTMP)
rm $PLOTTERTMP
rm $PLOTFTMP

# embed graph into template
TEMPLATE="
    \documentclass[12pt,letterpaper]{article}
    \usepackage{amsmath,amsthm,amsfonts,amssymb,amscd}
    \usepackage{fullpage}
    \usepackage{lastpage}
    \usepackage{fancyhdr}
    \usepackage{mathrsfs} 
    \usepackage{graphicx} 
    \pagestyle{fancyplain} 
    \headheight 35pt 
    \headsep 10pt
    \begin{document}
    \chead{\textbf{Hyun Sik Kim\ --- IB RESEARCH @ BROWN}}
    \noindent\makebox[\textwidth]{
    $PLOT
    } 
    \centerline{TODO (FILECONTENTS)} 
    \end{document} 
"

# typeset
touch "$OUTF.tex"
echo "$TEMPLATE" > "$OUTF.tex"
pdflatex "$OUTF.tex"


