#!/bin/bash


black='\E[30;200m'
red='\E[31;200m'
green='\E[32;200m'
yellow='\E[33;200m'
blue='\E[34;200m'
magenta='\E[35;200m'
cyan='\E[36;200m'
white='\E[37;200m'
cecho(){
    local default_msg="No message passed."
    message=${1:-$default_msg}  
    color=${2:-$black}
    echo -e "$color$message"
    tput sgr0
    return
}  

printhelp(){
    echo -e "DM: Data file Manager"
    echo -e "synopsis:"
    echo -e "append the string '#CHECK' to data files to mark them for commit"
    echo -e "marked data files pulled from bsn0* to sunlab machines for plotting\n"
    echo -e "usage:"
    echo -e "dm -l: show experiment types we have a '#CHECK'-ed file for"
    echo -e "dm -a: add '#CHECK'-ed files to git tracked files (equivalent to 'git add')"
    echo -e "dm -d: delete all data files without '#CHECK'"
    echo -e "dm -h: print this message"
}


# GET OPTIONS
while getopts ":ladh" opt; do
    case $opt in
        l)
            OPERATIONS="${OPERATIONS}l"
            ;;
        a)
            OPERATIONS="${OPERATIONS}a"
            ;;
        d)
            OPERATIONS="${OPERATIONS}d"
            ;;
        h)
            printhelp
            exit 1
            ;;
        \?)
            cecho "Invalid option: -$OPTARG" $red
            printhelp
            exit 1
            ;;
    esac
done

# CHECK ARGUMENTS FOR WELL-FORMEDNESS FIXME for now, everything is mutex
if [ ${#OPERATIONS} > 1 ]; then
    cecho "Invalid options combination -$OPERATIONS" $red
    printhelp
    exit 1
fi

# TODO -l command: find and list all files with the check mark '#CHECK'


